### PR TITLE
Task/dockerize

### PR DESCRIPTION
**Pull request by stevenzeiler**
Removing old non-docker ansible plays
Build image and push to quay.
Still lacks ansible deploy with docker, but I want to test this functionality.

### CODE REVIEW

**Comment by stevenzeiler** [comment]
:+1:

**Comment by wilsonianb** [comment]
It looks like this only pushes the docker image without then deploying.

**Comment by stevenzeiler** [comment]
That is correct. I want to make sure at least pushing to quay works correctly before moving on.

**Comment by wilsonianb** [comment]
LGTM :+1:

**Pull request merged**
